2025-01-23 15:19:55,090 INFO    MainThread:41042 [wandb_setup.py:_flush():68] Current SDK version is 0.19.4
2025-01-23 15:19:55,090 INFO    MainThread:41042 [wandb_setup.py:_flush():68] Configure stats pid to 41042
2025-01-23 15:19:55,091 INFO    MainThread:41042 [wandb_setup.py:_flush():68] Loading settings from /home/rohanb/.config/wandb/settings
2025-01-23 15:19:55,091 INFO    MainThread:41042 [wandb_setup.py:_flush():68] Loading settings from /home/rohanb/DiffusionToy/wandb/settings
2025-01-23 15:19:55,091 INFO    MainThread:41042 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-23 15:19:55,091 INFO    MainThread:41042 [wandb_init.py:setup_run_log_directory():624] Logging user logs to /home/rohanb/DiffusionToy/wandb/run-20250123_151955-q2b9q954/logs/debug.log
2025-01-23 15:19:55,091 INFO    MainThread:41042 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to /home/rohanb/DiffusionToy/wandb/run-20250123_151955-q2b9q954/logs/debug-internal.log
2025-01-23 15:19:55,091 INFO    MainThread:41042 [wandb_init.py:monkeypatch_ipython():576] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7003c2454140>
2025-01-23 15:19:55,091 INFO    MainThread:41042 [wandb_init.py:init():743] calling init triggers
2025-01-23 15:19:55,092 INFO    MainThread:41042 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {}
2025-01-23 15:19:55,092 INFO    MainThread:41042 [wandb_init.py:init():776] starting backend
2025-01-23 15:19:55,305 INFO    MainThread:41042 [wandb_init.py:init():780] sending inform_init request
2025-01-23 15:19:55,311 INFO    MainThread:41042 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-23 15:19:55,312 INFO    MainThread:41042 [wandb_init.py:init():795] backend started and connected
2025-01-23 15:19:55,316 INFO    MainThread:41042 [wandb_run.py:_label_probe_notebook():1213] probe notebook
2025-01-23 15:19:55,321 INFO    MainThread:41042 [wandb_init.py:init():888] updated telemetry
2025-01-23 15:19:55,327 INFO    MainThread:41042 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-23 15:19:55,527 ERROR   MainThread:41042 [wandb_init.py:init():944] encountered error: failed to upsert bucket: returned error 400 Bad Request: {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-23 15:19:55,527 ERROR   MainThread:41042 [wandb_init.py:init():1454] error in wandb.init()
Traceback (most recent call last):
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 400 Bad Request: {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-23 15:20:49,543 INFO    MainThread:41042 [wandb_init.py:setup_run_log_directory():624] Logging user logs to /home/rohanb/DiffusionToy/wandb/run-20250123_152049-tl2gwo4z/logs/debug.log
2025-01-23 15:20:49,543 INFO    MainThread:41042 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to /home/rohanb/DiffusionToy/wandb/run-20250123_152049-tl2gwo4z/logs/debug-internal.log
2025-01-23 15:20:49,544 INFO    MainThread:41042 [wandb_init.py:init():743] calling init triggers
2025-01-23 15:20:49,544 INFO    MainThread:41042 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {}
2025-01-23 15:20:49,544 INFO    MainThread:41042 [wandb_init.py:init():776] starting backend
2025-01-23 15:20:49,544 INFO    MainThread:41042 [wandb_init.py:init():780] sending inform_init request
2025-01-23 15:20:49,546 INFO    MainThread:41042 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-23 15:20:49,549 INFO    MainThread:41042 [wandb_init.py:init():795] backend started and connected
2025-01-23 15:20:49,550 INFO    MainThread:41042 [wandb_run.py:_label_probe_notebook():1213] probe notebook
2025-01-23 15:20:49,553 INFO    MainThread:41042 [wandb_init.py:init():888] updated telemetry
2025-01-23 15:20:49,558 INFO    MainThread:41042 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-23 15:21:33,324 WARNING MainThread:41042 [wandb_init.py:init():1448] interrupted
Traceback (most recent call last):
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 920, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-01-23 15:22:31,494 INFO    MainThread:41042 [wandb_init.py:setup_run_log_directory():624] Logging user logs to /home/rohanb/DiffusionToy/wandb/run-20250123_152231-44wsaevo/logs/debug.log
2025-01-23 15:22:31,494 INFO    MainThread:41042 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to /home/rohanb/DiffusionToy/wandb/run-20250123_152231-44wsaevo/logs/debug-internal.log
2025-01-23 15:22:31,495 INFO    MainThread:41042 [wandb_init.py:init():743] calling init triggers
2025-01-23 15:22:31,495 INFO    MainThread:41042 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {}
2025-01-23 15:22:31,495 INFO    MainThread:41042 [wandb_init.py:init():776] starting backend
2025-01-23 15:22:31,495 INFO    MainThread:41042 [wandb_init.py:init():780] sending inform_init request
2025-01-23 15:22:31,498 INFO    MainThread:41042 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-23 15:22:31,499 INFO    MainThread:41042 [wandb_init.py:init():795] backend started and connected
2025-01-23 15:22:31,501 INFO    MainThread:41042 [wandb_run.py:_label_probe_notebook():1213] probe notebook
2025-01-23 15:22:31,504 INFO    MainThread:41042 [wandb_init.py:init():888] updated telemetry
2025-01-23 15:22:31,509 INFO    MainThread:41042 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-23 15:22:45,656 WARNING MainThread:41042 [wandb_init.py:init():1448] interrupted
Traceback (most recent call last):
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 920, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohanb/DiffusionToy/diffusion_toy/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
